### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NotRel** [sinkaroid/janda#4]
```
https://janda.mod.land/nhentai/search?key=xxx&page=1&sort=popular-today 503
```

**Comment by sinkaroid** [comment]
I got this, the issue is related to the railway itself, and I cannot reproduce for it's overload and fair-use in every months, gonna remake and find the alternative asap

**Comment by smyhlin** [comment]
Good luck, nice project

**Comment by sinkaroid** [comment]
Upgrade your module to `__version__ = "3.1.3"` that was fixed
